name: Stats & Comments
on:
  page_build:
  issues:
    types: [opened, edited]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: 浏览量统计
        run: |
          PV=$(cat pv.txt 2>/dev/null || echo 0)
          NEW_PV=$((PV + 1))
          echo $NEW_PV > pv.txt
          echo "当前浏览量：$NEW_PV"
          
      - name: 上传浏览量
        uses: actions
